blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/Lavelliane/xylvir-light/discussions
    about: Use discussions for questions and general help
  - name: ðŸ“š Documentation
    url: https://github.com/Lavelliane/xylvir-light#readme
    about: Check our documentation first

